### PR TITLE
Make sure RegistrationTool.addMember is not published

### PR DESCRIPTION
**Pull request by vangheem**
See https://pypi.python.org/pypi/Products.PloneHotfix20150910

### CODE REVIEW

**Comment by vangheem** [comment]
jenkins plone tests running here: http://jenkins.plone.org/job/pull-request-5.0/287/

**Comment by vangheem** [comment]
This is ready to merge.

**Comment by tseaver** [comment]
If it isn't supposed to be publishable, then the `@postonly` decorator should go, too (it requires that the request have 'POST' as its method).

**Comment by vangheem** [comment]
Yes. I'll update.

**Comment by mauritsvanrees** [comment]
Tests pass. I will merge. I will also have a look at the other CMFCore branches.

**Comment by mauritsvanrees** [comment]
Merged to master too.

**Pull request merged**
