### PR TITLE
URLTool: fix acquisition context for getPortalObject

### PR DESCRIPTION
**Pull request by perrinjerome**
Use logic from a CMFCore.CMFPlone patch
https://github.com/plone/Products.CMFPlone/pull/2205

see https://github.com/plone/Products.CMFPlone/issues/2194

### CODE REVIEW

**Comment by perrinjerome** [comment]
@pbauer @davisagli I am here "moving" one of your patch for the issue from https://github.com/plone/Products.CMFPlone/issues/2194 - the issue is not really specific to plone, so it's better to have it here I guess. Is it OK to take this commit here ? do you want me to add "co-authored by" or something ? 

Thanks in advance !


For the records, I observed the issue with something like this:

```py
portal = context.portal_url.getPortalObject()
portal.restrictedTraverse(portal.getPhysicalPath()).REQUEST   # <- AttributeError REQUEST
```

**Comment by davisagli** [comment]
@perrinjerome I don't remember the details of why this is necessary, but I'm fine with adapting the code from CMFPlone for CMFCore.

**Comment by perrinjerome** [comment]
Thanks ! 

The problem is that the acqusition context is not correct, only the portal is in the context of the request container, but the rest of the chain is not, so when using something like 

```py
portal_url.getPortalObject().restrictedTraverse(('', 'Plone')) # notice the first ''
```

`restrictedTraverse` will use `getPhysicalRoot` ( [here](https://github.com/zopefoundation/Zope/blob/73d2dfcce2637af7780205a6b6146b9beffbb255/src/OFS/Traversable.py#L196-L198) ) and this `getPhysicalRoot` is the `<Application at >`, but not in the acqusition context (because only the portal is). This was the problem I saw, but there might be other consequences, basically it seems that this patch was not solving a plone problem, but a CMFCore problem, so it seems better to have it here.

**Comment by dataflake** [comment]
I am not comfortable with this change. You're changing the semantics of a method that has been unchanged for 12 years. I would add a separate method for what you're trying to achieve and that other method should not use a utility lookup.

**Comment by perrinjerome** [comment]
Thanks for the feedback.

I noticed this when updating from `Products.CMFCore` 2.2.x, this behavior changed between 2.2 and 2.3. If we consider the releases, the first "not beta" release where `queryUtility` was used  is 2.3.0, which was released on 2015-02-20, this is bit less than 12 years, but still a long time ago.

I thought that this was just a bug (because it was a bug for me and it was a bug for Plone) and that fixing it here would be better because anyway plone had a monkey patch doing the same as this change, but you are right, it's not impossible that bringing this change now break something or impact performance.

Unless others think that it's better to have this change, we can close this pull request. 

On my side I think I will change to not register the portal as `ISiteRoot`, then this method will have the same behavior as with CMFCore 2.2

**Comment by icemac** [comment]
I do not feel competent enough to review this PR.

**Comment by dataflake** [comment]
I'll just close the request and my suggestion still stands: If a fix is desired in `Products.CMFCore` it should be based on an additional method that returns the fully-wrapped portal object. The old method should remain unchanged.

**Pull request closed without merging**
