### PR TITLE
Minor cleanup

### PR DESCRIPTION
**Pull request by gforcada**
This pull request does two minimal things:

- remove a deprecated import (zope.app.publication)
- removes eggtestinfo from test_requires

### CODE REVIEW

**Comment by dataflake** [comment]
Gil, why is this needed for the 2.2 branch? You would also need to move the base requirement to Zope 2.13 on the branch for it to work.

**Comment by dataflake** [comment]
Is there a reason to remove the eggtestinfo dependency?

**Comment by gforcada** [comment]
@dataflake I guess I did this pull request because this branch (2.2) is still being used by some Plone version.

As for the eggtestinfo dependency, I couldn't see it used anywhere, so I removed it. It is useful? I've never seen it on any plone setup.py.

**Comment by tseaver** [comment]
> this branch (2.2) is still being used by some Plone version.

We cannot force such downstream projects to upgrade to Zope 2.13.x.

`eggtestinfo` could be pulled out on `master` in a separate PR.

**Pull request closed without merging**
