### PR TITLE
Configure travis integration.

### PR DESCRIPTION
**Pull request by icemac**

### CODE REVIEW

**Comment by icemac** [comment]
After pinning the versions to Zope < 4 and ZODB < 5 (see zopefoundation/Zope#79) many tests fail.
Is there anyone with deeper CMFCore knowledge to help fixing this?

**Comment by mauritsvanrees** [comment]
This test is trying to add a DTML Method to a folder that does not allow this meta type:

```
(Pdb) object.meta_type
'DTML Method'
(Pdb) self
<Folder at portal_skins/custom>
(Pdb) self.meta_type
'Folder'
(Pdb) self.__class__
<class 'OFS.Folder.Folder'>
(Pdb) pp [x['name'] for x in self.all_meta_types()]
['ZCTextIndex Lexicon',
 'Filesystem Directory View',
 'Cookie Crumbler',
 'Content Type Registry',
 'CMF Caching Policy Manager',
 'CMF Core Tool',
 'Page Template',
 'Script (Python)',
 'Z SQL Method',
 'Z Search Interface']
```

I don't know what has changed to make this fail.

But when I make the buildout look more like in [CMF-buildout](https://github.com/zopefoundation/CMF-buildout/blob/master/buildout-zope213.cfg) it goes better:

```
[buildout]
extends =
    http://download.zope.org/zopetoolkit/index/1.0.8/zopeapp-versions.cfg
    http://download.zope.org/Zope2/index/2.13.22/versions.cfg
develop = .
parts =
    test
    zopepy
    sphinx

unzip = true


[test]
recipe = zc.recipe.testrunner
eggs = Products.CMFCore


[versions]
# Newer zc.buildout gives better conflict error messages,
# and it somehow avoids an error during installing of zc.recipe.testrunner.
# You do need a newer bootstrap.py that can handle zc.buildout 2.
zc.buildout = 2.5.3
setuptools = 32.1.0
Zope2 = < 4
Products.PythonScripts = < 4
Products.ZCTextIndex = < 4
ZODB = < 5
ZEO = < 5
transaction = < 2


[zopepy]
recipe = zc.recipe.egg
eggs =
    Products.CMFCore
interpreter = zopepy
scripts = zopepy


[sphinx]
recipe = zc.recipe.egg
eggs =
    Products.CMFCore
    Sphinx
    repoze.sphinx.autointerface
    pkginfo
```

That gives less test errors, although there are still some. But the CMF-buildout also gives test errors.
Those problems may need a different ZODB or transaction version:

```
Error in test test_customize_alternate_root (Products.CMFCore.tests.test_FSSTXMethod.FSSTXMethodCustomizationTests)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 358, in run
    self.tearDown()
  File "/Users/maurits/community/CMF-master/develop/Products.CMFCore/Products/CMFCore/tests/test_FSSTXMethod.py", line 194, in tearDown
    _TemplateSwitcher.tearDown(self)
  File "/Users/maurits/community/CMF-master/develop/Products.CMFCore/Products/CMFCore/tests/test_FSSTXMethod.py", line 87, in tearDown
    self._setWhichTemplate(self._old_STX_TEMPLATE)
  File "/Users/maurits/community/CMF-master/develop/Products.CMFCore/Products/CMFCore/tests/test_FSSTXMethod.py", line 101, in _setWhichTemplate
    self.app._setOb('main_template', main)
  File "/Users/maurits/shared-eggs/Zope2-2.13.24-py2.7.egg/OFS/ObjectManager.py", line 288, in _setOb
    setattr(self, id, object)
  File "/Users/maurits/shared-eggs/ZODB-4.4.4-py2.7.egg/ZODB/Connection.py", line 1026, in register
    self._register(obj)
  File "/Users/maurits/shared-eggs/ZODB-4.4.4-py2.7.egg/ZODB/Connection.py", line 1036, in _register
    self.transaction_manager.get().join(self)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by mauritsvanrees** [comment]
Actually, it is easy: don't use ZODB and ZEO.  Remove those from the `setup.py` and the buildout again and all is fine. Compatibility with those can be handled later.

The buildout should extend these:

```
extends =
    http://download.zope.org/zopetoolkit/index/1.0.8/zopeapp-versions.cfg
    http://download.zope.org/Zope2/index/2.13.22/versions.cfg
# or newer http://dist.plone.org/versions/zope-2-13-24-versions.cfg
# but this gives a constraint error for mechanize.
```

And the `zopepy` part can simply be this:

```
[zopepy]
recipe = zc.recipe.egg
eggs =
    Products.CMFCore
# or Zope2 as before, but using CMFCore seems saner.
interpreter = zopepy
scripts = zopepy
```

**Comment by icemac** [comment]
@mauritsvanrees Thanks a lot, your hints helped to get it green again locally.

**Comment by mauritsvanrees** [comment]
Good! Oh, your `zopepy` now only has `Products.GenericSetup`. That should be `Products.CMFCore`.

**Comment by icemac** [comment]
@mauritsvanrees Good catch. :)

**Pull request merged**
