### PR TITLE
Prevent warnings on Zope start about permissions for not existing methods.

### PR DESCRIPTION
**Pull request by icemac**
The warnings look like this:

```
2018-11-08 16:40:03 WARNING Init Class Products.CMFCore.PortalContent.PortalContent has a security declaration for nonexistent method 'manage_FTPlist'
2018-11-08 16:40:03 WARNING Init Class Products.CMFCore.PortalContent.PortalContent has a security declaration for nonexistent method 'manage_FTPstat'
```

### CODE REVIEW

**Comment by davisagli** [comment]
Wouldn't it make things simpler to add the security declarations in OFS.SimpleItem?

**Comment by icemac** [comment]
@tseaver What do you think about the suggestion of @davisagli? Do you know the reason why this was not done on `OFS.SimpleItem` in the first place?

**Comment by tseaver** [comment]
Seems reasonable to me to fix the underlying problem, rather than papering over it.

**Comment by icemac** [comment]
Changed to depend on Zope providing the necessary security declarations.

**Comment by sallner** [comment]
Why did this commit https://github.com/zopefoundation/Zope/commit/0ad67e74c7797f6b2ef170368c8f4e371b250ac7 successfully passed travis? There were some allowed failures, but I can't see, where they were introduced.

**Comment by icemac** [comment]
Locally each of the commits was green. So I have to investigate what's different on TravisCI.

**Comment by icemac** [comment]
I'd like to keep this PR open until 
https://github.com/zopefoundation/Products.GenericSetup/pull/77 is fixed and released.

**Pull request merged**
