### PR TITLE
Test against Zope 5.

### PR DESCRIPTION
**Pull request by icemac**
Python 2.7 and 3.5 are still tested against Zope 4, the newer versions against Zope 5.

Could this be a way to go to keep Python 2 and Zope 4 support while also testing against Zope 5?

### CODE REVIEW

**Comment by dataflake** [comment]
This could be a way and I like the idea, but the errors show you it needs tweaking. I looked at the output of the Python 3.5 run and it seems Zope 4.5.1 was installed, but then there are syntax errors coming out of a Zope 5.0 egg. So the sandbox still pulls in Zope 5 somwhere.

**Comment by dataflake** [comment]
I still see this in the output:

```
<...>
Got Products.ZCatalog 6.0.
Getting distribution for 'Zope>=4.0b8'.
Got Zope 5.0.
<...>
```

**Comment by dataflake** [comment]
The buildout process seems to run twice:

```
<...>
Got WebOb 1.8.6.
Generated script '/home/travis/build/zopefoundation/Products.CMFCore/.tox/py35/bin/test'.
py35 run-test-pre: commands[1] | /home/travis/build/zopefoundation/Products.CMFCore/.tox/py35/bin/buildout -nc /home/travis/build/zopefoundation/Products.CMFCore/buildout.cfg buildout:directory=/home/travis/build/zopefoundation/Products.CMFCore/.tox/py35 buildout:develop=/home/travis/build/zopefoundation/Products.CMFCore install test
Develop: '/home/travis/build/zopefoundation/Products.CMFCore'
Getting distribution for 'zope.exceptions==4.4'.
Got zope.exceptions 4.4.
Uninstalling test.
Installing test.
Getting distribution for 'Products.ZCatalog==6.0'.
Got Products.ZCatalog 6.0.
Getting distribution for 'Zope>=4.0b8'.
Got Zope 5.0.
<...>
```

**Comment by icemac** [comment]
I seem to have fixed it by now. The tox syntax for `not` is surprising.
Sorry for the many commits, but locally Python 3.5 does not run. It breaks when running buildout because of `AttributeError: '_NamespacePath' object has no attribute 'sort'` when trying to install `zc.recipe.testrunner`.

**Comment by dataflake** [comment]
Looks like it works. I wonder if it is possible to override the buildout `extends` right in the invocation in `tox.ini` to save the second buildout configuration file?

**Comment by dataflake** [comment]
FYI: I cannot reproduce the local tox failure you mentioned. In an existing buildout I pulled your branch, deleted the `.tox` folder and ran `/bin/tox -pall`. It worked fine.

**Review by dataflake — APPROVED** [review]
This is ready to go. I experimented a little trying to get around the second buildout configuration file, but it doesn't seem possible to pass something like `... buildout:extends=URL ...` on the command line.

**Pull request merged**
