### PR TITLE
Collective indexing master

### PR DESCRIPTION
**Pull request by gforcada**
Same as https://github.com/zopefoundation/Products.CMFCore/pull/12 for master branch.

### CODE REVIEW

**Comment by gforcada** [comment]
Would anyone mind to merge this? The pull request #12 for merging it to branch 2.2 has been long merged.

**Comment by tseaver** [comment]
#12 was actually merged a bit prematurely:  the concern about generating a class on the fly in `indexing.wrap()` wasn't addressed.

Looking at it today, that part of the code is completely uncovered by tests: `unindex()` is only ever tested with simple strings, which short-circuit out of `wrap()`.

**Comment by dataflake** [comment]
I have improved the indexing.wrap method on the 2.2 branch in commit e89a0d8 and will use that as a base line for trying to forward-port this PR to the 2.3 and master branches.

**Comment by dataflake** [comment]
What the pull request attempts to do has been merged and improved "manually" in the following commits:

e89a0d897d45df9011de29017b98e83fd44ea4db for the 2.2 branch to improve the unindex wrapping and address Tres' comment
f8013c6e0f3e57a702482b8d50329946417bf621 for the master branch
34b7ee86ea13b5df42f022f8d7868c73672c9817 for the 2.3 branch

**Comment by dataflake** [comment]
Closing the pull request, the work has been done outside of this PR

**Comment by gforcada** [comment]
@dataflake thanks!

**Pull request closed without merging**
