### PR TITLE
fix content export in py3 when readDataFile returns bytes

### PR DESCRIPTION
**Pull request by pbauer**

### CODE REVIEW

**Comment by pbauer** [comment]
I added a changenote buty a test is more complex because the case where readDataFile uses ZipFile  and returns bytes is in plone.app.dexterity. These feature in plone.app.dexterity is incomplete, probably not used at all by anyone and has no tests that deserve that name. 
So I suggest we leave this PR lie around until the feature is at least tested in plone.app.dexterity and use the current version of Products.CMFCore in Plone 5.2.

**Comment by gforcada** [comment]
@pbauer @jensens if you want a release of 5.2 this should be resolved :sweat_smile:

**Comment by icemac** [comment]
Is this PR still valid? It seems not to be needed for Plone 5.2 – or did I miss something?

**Comment by icemac** [comment]
I'd suggest to close this PR. A similar looking problem was handled in #116.
@dataflake Do you agree?

**Comment by dataflake** [comment]
I agree. `readDataFile` **always** returns bytes, which is now documented better in the GS interfaces.

**Pull request closed without merging**
